import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val appcompat: String = "1.1.0"

  const val constraintlayout: String = "1.1.3"

  const val recyclerview: String = "1.1.0"

  const val aapt2: String = "3.5.2-5435860"

  const val com_android_tools_build_gradle: String = "3.5.2"

  const val lint_gradle: String = "26.5.2"

  const val timber: String = "4.7.1"

  const val executioner: String = "1.0.1"

  const val permission_bitte: String = "0.5.0" // available: "1.0.2"

  const val gradle_maven_publish_plugin: String = "0.8.0"

  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.5.0" // available: "0.7.0"

  const val scanner: String = "1.4.3"

  const val org_jetbrains_kotlin: String = "1.3.60"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "6.0.1"

  const val gradleCurrentVersion: String = "5.6.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
      id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
